title: mc095
description: Series of Blogs of my linux learning
baseurl: "" # Keep empty for local development
url: "https://mc095.github.io"
paginate: 8
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
  
markdown: kramdown
highlighter: rouge

# Sort posts by date in ascending order (oldest first)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

keep_files:
  - .git
  - .svn
  - assets

# Disable caching
sass:
  style: expanded
  sourcemap: development

# Enable file watching
force_polling: true

# Development settings
development:
  baseurl: ""
  url: "http://localhost:4000"